name: Run tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Pack Chocolatey package
        shell: pwsh
        run: choco pack duo-auth-proxy.nuspec --outputdirectory packages

      - name: Run tests
        shell: pwsh
        run: ./tests/run-tests.ps1
